<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Set up Two-Factor Authentication</title>
    <!-- Load Tailwind CSS CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        /* Apply the Inter font for a modern look */
        body {
            font-family: 'Inter', sans-serif;
        }
        /* Custom style for the QR code placeholder box */
        .qr-placeholder {
            width: 200px;
            height: 200px;
            background-color: #f7f7f7;
            border: 2px solid #e2e8f0;
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
</head>
<body class="bg-gray-100 antialiased">

    <!-- The main layout container, replicating the Blade section content -->
    <div class="min-h-screen flex items-center justify-center">
        <div class="bg-white shadow-xl rounded-2xl w-full max-w-md p-8 m-4">
            
            <!-- Header -->
            <h2 class="text-3xl font-extrabold text-gray-800 mb-2 text-center">Setup Two-Factor Authentication</h2>
            <p class="text-gray-500 mb-6 text-center text-sm">
                Scan this QR code in your Google Authenticator app or compatible TOTP app.
            </p>

            <!-- QR Code Container (Placeholder for $qrCodeSvg) -->
            <div class="flex justify-center mb-6">
                <!-- 
                    In a real application, the QR Code SVG generated by the server would be here.
                    This is a visual placeholder: 
                -->
                <div class="qr-placeholder transition duration-300 hover:shadow-inner">
                    <svg class="text-gray-400 w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
                    </svg>
                    <span class="absolute text-xs font-semibold text-gray-600">QR CODE HERE</span>
                </div>
            </div>

            <p class="text-gray-600 mb-8 text-center">
                Then enter the 6-digit code generated by the app below to verify.
            </p>

            <!-- Verification Form -->
            <form action="/admin/2fa/setup/verify" method="POST" class="space-y-6">
                <!-- Note: @csrf removed for static HTML -->
                
                <div>
                    <label for="otp" class="block text-sm font-medium text-gray-700 mb-2">Authentication Code</label>
                    <input 
                        type="text" 
                        name="otp" 
                        id="otp" 
                        maxlength="6" 
                        placeholder="123456"
                        pattern="\d{6}"
                        class="w-full px-4 py-3 border border-gray-300 rounded-lg shadow-sm text-lg text-center tracking-widest focus:outline-none focus:ring-4 focus:ring-blue-200 focus:border-blue-500 transition duration-150" 
                        required
                    >
                    
                    <span class="text-red-600 text-sm mt-1 block hidden">The provided code is invalid.</span>
                    
                </div>

                <button 
                    type="submit"
                    class="w-full bg-blue-600 text-white py-3 rounded-lg font-bold text-base shadow-lg hover:bg-blue-700 hover:shadow-xl focus:outline-none focus:ring-4 focus:ring-blue-300 transition duration-200 ease-in-out">
                    Verify & Enable 2FA
                </button>
            </form>
        </div>
    </div>
</body>
</html>